/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Destination = IDL.Record({
  'id' : IDL.Nat,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'destinationType' : IDL.Text,
  'highlights' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'price' : IDL.Nat,
});
export const Package = IDL.Record({
  'id' : IDL.Nat,
  'durationDays' : IDL.Nat,
  'title' : IDL.Text,
  'destinationId' : IDL.Nat,
  'isPopular' : IDL.Bool,
  'inclusions' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDestination' : IDL.Func([Destination], [IDL.Nat], []),
  'addFavorite' : IDL.Func([IDL.Nat], [], []),
  'addPackage' : IDL.Func([Package], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDestination' : IDL.Func([IDL.Nat], [], []),
  'deletePackage' : IDL.Func([IDL.Nat], [], []),
  'getAllDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDestinationsByMaxPrice' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Destination)],
      ['query'],
    ),
  'getDestinationsByType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Destination)],
      ['query'],
    ),
  'getFavorites' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFavorite' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDestination' : IDL.Func([IDL.Nat, Destination], [], []),
  'updatePackage' : IDL.Func([IDL.Nat, Package], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Destination = IDL.Record({
    'id' : IDL.Nat,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'destinationType' : IDL.Text,
    'highlights' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'price' : IDL.Nat,
  });
  const Package = IDL.Record({
    'id' : IDL.Nat,
    'durationDays' : IDL.Nat,
    'title' : IDL.Text,
    'destinationId' : IDL.Nat,
    'isPopular' : IDL.Bool,
    'inclusions' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDestination' : IDL.Func([Destination], [IDL.Nat], []),
    'addFavorite' : IDL.Func([IDL.Nat], [], []),
    'addPackage' : IDL.Func([Package], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDestination' : IDL.Func([IDL.Nat], [], []),
    'deletePackage' : IDL.Func([IDL.Nat], [], []),
    'getAllDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDestinationsByMaxPrice' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Destination)],
        ['query'],
      ),
    'getDestinationsByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Destination)],
        ['query'],
      ),
    'getFavorites' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFavorite' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDestination' : IDL.Func([IDL.Nat, Destination], [], []),
    'updatePackage' : IDL.Func([IDL.Nat, Package], [], []),
  });
};

export const init = ({ IDL }) => { return []; };