/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Destination {
  'id' : bigint,
  'country' : string,
  'name' : string,
  'description' : string,
  'destinationType' : string,
  'highlights' : Array<string>,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'price' : bigint,
}
export interface Package {
  'id' : bigint,
  'durationDays' : bigint,
  'title' : string,
  'destinationId' : bigint,
  'isPopular' : boolean,
  'inclusions' : Array<string>,
  'imageUrl' : string,
  'price' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDestination' : ActorMethod<[Destination], bigint>,
  'addFavorite' : ActorMethod<[bigint], undefined>,
  'addPackage' : ActorMethod<[Package], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDestination' : ActorMethod<[bigint], undefined>,
  'deletePackage' : ActorMethod<[bigint], undefined>,
  'getAllDestinations' : ActorMethod<[], Array<Destination>>,
  'getAllPackages' : ActorMethod<[], Array<Package>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDestinationsByMaxPrice' : ActorMethod<[bigint], Array<Destination>>,
  'getDestinationsByType' : ActorMethod<[string], Array<Destination>>,
  'getFavorites' : ActorMethod<[], Array<Destination>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFavorite' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDestination' : ActorMethod<[bigint, Destination], undefined>,
  'updatePackage' : ActorMethod<[bigint, Package], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];